### ISSUE TITLE
Having problems with installing pmatch in 3.6.0

### ISSUE THREAD

**Issue by scra88le** [mailund/pmatch#70]
I have installed the dev version of pmatch. When I load the library I get:

```
> library(pmatch)
Warning message:
replacing previous import ‘vctrs::data_frame’ by ‘tibble::data_frame’ when loading ‘dplyr’ 
> library(magrittr)
> zero_one_two_three := ZERO | ONE(x) | TWO(x,y) | THREE(x,y,z)
> TWO(1,2)
Error: Input must be a vector, not a `zero_one_two_three` object.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/vctrs_error_scalar_type>
Input must be a vector, not a `zero_one_two_three` object.
Backtrace:
  1. (function (x, ...) ...
 11. vctrs:::stop_scalar_type(...)
 12. vctrs:::stop_vctrs(msg, "vctrs_error_scalar_type", actual = x)

```

Is this because I'm running r 3.6.0 ? And is there anything I can do to address?

Thanks

**Comment by lebensterben** [comment]
It doesn't work on R 4.3 either.
Probably there are API changes in rlang or other dependencies so it doesn't work any more.

```
> install.packages("pmatch")
Installing package into ‘/home/lucius/R/x86_64-generic-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘pmatch’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

**Comment by mailund** [comment]
Yeah, the problem is that some of the packages that `pmatch` uses now do some type checking that clashes with how I use types. And unfortunately, I haven't had time to update things. I keep planning to get back to it, but other obligations keep getting in the way. My teaching load is much smaller in the spring, so I might be able to look at it there--I hope so--but I have a book deadline so it will be a month or two before I can. Sorry.

**Comment by scra88le** [comment]
What version of r does it work with? Your DSL book is great, btw.
Thanks

**Comment by mailund** [comment]
It is not so much the version of R as it is the version of the libraries I use. I rely heavily on some tidyverse packages, such as `rlang`, and that is the issue. I will check and try to fix it as soon as I can.

A bigger issue is that the library is pretty slow. I made it substantially faster since the code from the DSL book (happy you liked it!), but it is still too slow for implementing fast data structures. I had hoped that there would be enough gained by using better data structures, and the overhead wouldn't be so much of an issue, but I am not quite there.

The issue is that I have to run a small program every time I pattern match. I need to compare the input with a patter every time--even though the newer code doesn't try to interpret the pattern DSL at call time any longer, but handles it when you define a function. So my thought was that I could move that part to C. That was more than a year ago, but I simply didn't have the time to get it up and running. It is still on my wish list, and I do hope I will get there someday, but I have no idea about when that day may come.

**Comment by scra88le** [comment]
ok, thanks for getting back to me. I've fired up ghci in the mean time...
